### ISSUE TITLE
Add fingerprint / face to an already created user

### ISSUE THREAD

**Issue by nk-alex** [supremainc/BioStar2_device_SDK#26]
My case is the following.

I would like to use **BS2_ScanFingerprintEx** and **BS2_ScanFace** to put the device in read mode. Once the fingerprint of face is scaned, I would like to retreive this information and assign it to a user in my end. After all this process, I'm going to call myself **BS2_EnrolUser** to register this user into the device with the generated **BS2UserBlob**.

Is it possible?

**Comment by mphoradio** [comment]
Hi there,

Thank you for your email.

Please note that I am currently on leave for the festive season holidays and unable to attend to your enquiry.

I will resume work on the 8th of January 2024 and look forward to getting back to you promptly upon my return.

Thank you for your support over the past year and I wish you and your family a safe and happy holiday season.

Kind Regards
Paul
