### ISSUE TITLE
BioMini USB

### ISSUE THREAD

**Issue by leobackes** [supremainc/BioStar2_device_SDK#5]
Hello,

I'm trying to integrate with an USB BioMini through this library, I don't know if it is the correct one, but couldn't find any other.
Currently I'm on ArchLinux, but I'm also targeting Windows.

Made some tests, most of them without success, hence my questions:

* What is the correct parameter for `BS2_AllocateUsbContext`? If I point it to /dev/bus/usb, `BS2_Initialize` gives success, but `BS2_SearchDevices` returns BS_SDK_ERROR_SOCKET_IN_PROGRESS. If I point it directly to the USB as /dev/bus/usb/001/010, the library freezes on `BS2_Initialize`.

* What is the correct sequence to capture the image, and which format is it given? My goal is exclusively to capture the fingerprint image, I don't want any of the feature extratcions or use the device's memory.

* Is any other update to this library in regards to OpenSSL? `SSLv3_server_method` was deprecated and is not present in recent releases anymore, so I had to add the symbol myself, which is not a desirable hack.

Thanks in advance.

**Comment by suprema-charlie** [comment]
The purpose of the USB connection in the BioStar Device SDK is to support the extraction of the device log from the biometric recognition device to the USB memory and the import of the log of the USB memory from the BioStar Device SDK.
It is possible regardless of functions such as capturing the desired fingerprint image.

BS2_AllocateUsbContext may be helpful if you refer to the article in the link below.
(http://kb.supremainc.com/bs2sdk/doku.php?id=en:use_exported_control_api)

BS2_SearchDevice is a function that searches for devices on Ethernet.
It is a function independent of USB.

If you have any questions related to BioMini, please contact support_id@supremainc.com
