### ISSUE TITLE
SDK Not Supported for SetAuthOperatorLevelEx

### ISSUE THREAD

**Issue by nosratiz** [supremainc/BioStar2_device_SDK#8]
when want to set Auth level for user biostation a2  return Sdk Not Supported

**Comment by suprema-charlie** [comment]
How much is you FW version?
This function is supported from version 1.7.0 based on BSA2.
If supported from an older version of the device, Not supported may be returned.
If the version is lower, the device must be upgraded first.
This contents is Revision Notes of BSA2.
![image](https://user-images.githubusercontent.com/50222995/89152136-7358c280-d59d-11ea-8c06-2e11cc3cb8ae.png)
